#!/bin/tcsh
unset noclobber

set MODIFIEDBEAMLINE = $1
set TRIAL = $2

sed "s/rootname=$MODIFIEDBEAMLINE/rootname=$MODIFIEDBEAMLINE$TRIAL/g" $RDPATH/$MODIFIEDBEAMLINE.ele > $ELEGANTPATH/$MODIFIEDBEAMLINE$TRIAL.ele

sed -i "s/lattice=$MODIFIEDBEAMLINE/lattice=$MODIFIEDBEAMLINE$TRIAL/g" $ELEGANTPATH/$MODIFIEDBEAMLINE$TRIAL.ele
