#!/bin/tcsh
unset noclobber

sed "s/use_beamline=$MODIFIEDBEAMLINE/use_beamline=$MODIFIEDBEAMLINE$TRIAL/g"; "s/rootname=$MODIFIEDBEAMLINE/rootname=$MODIFIEDBEAMLINE$TRIAL/g"; "s/lattice=$MODIFIEDBEAMLINE/lattice=$MODIFIEDBEAMLINE$TRIAL/g" $RDPATH/$MODIFIEDBEAMLINE.ele > $ELEGANTPATH/$MODIFIEDBEAMLINE$TRIAL.ele
